### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by PackageInstaller** [istrashguy/nonebot_plugin_Imagelabels#3]
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/6edfb5eb-692a-435b-b0ef-af56c081401b)
问题：发送图片标注后，发送了两张一样的图片
期望：一张就好了，但是不明白是哪里的问题
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/b1f44b3e-c301-4298-b654-f9fade4c4d17)
配置如上图

另，加载插件时消息提示：
```
可能由于没有权限所引发的异常，请尝试以管理员/root 身份运行bot,以讲错误追加到 Imagelabels-err.txt 
 错误代码：001 
 Possibly because of an exception thrown by not having permissions, try running bot as administrator/root to append the error to the Imagelabels-err.txt 
 Error code: 001
可能由于没有权限所引发的异常，请尝试以管理员/root 身份运行bot,以讲错误追加到 Imagelabels-err.txt 
 错误代码：001 
 Possibly because of an exception thrown by not having permissions, try running bot as administrator/root to append the error to the Imagelabels-err.txt 
 Error code: 001
```

系统是Arch linux ，整个bot目录以及目录下所有文件/文件夹都有可读写权限，且用户和用户组都为普通用户，用sudo python bot.py还是会有上述问题，检查 `Imagelabels-err.txt`  ，里面的报错都是

`Fri Jun  2 15:28:33 2023:[Errno 2] No such file or directory: '/home/Neko/Bot/zhenxun_bot/yolov5-master/runs/detect'Fri Jun  2 15:28:33 2023:[Errno 2] No such file or directory: '/home/Neko/Bot/zhenxun_bot/yolov5/runs/detect'`

但是我手动创建detect文件夹，启动后都会自己消失

**Comment by PackageInstaller** [comment]
重装了一下，还是 `以讲错误追加到 Imagelabels-err.txt` 这个提示，但是这个提示中以讲两个错别字只有在插件的recover.py中才有，去看了一下yolov5-master/runs这个文件夹，777权限不可能会创建文件夹失败，而且插件是能正常使用的，就很迷惑，究竟是哪里的问题？
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/bd1e9c32-255c-441e-a397-64f8b203d9f6)

**Comment by Heartestrella** [comment]
> 重装了一下，还是 `以讲错误追加到 Imagelabels-err.txt` 这个提示，但是这个提示中以讲两个错别字只有在插件的recover.py中才有，去看了一下yolov5-master/runs这个文件夹，777权限不可能会创建文件夹失败，而且插件是能正常使用的，就很迷惑，究竟是哪里的问题？
> ![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/bd1e9c32-255c-441e-a397-64f8b203d9f6)
> 
你指的是发送两张相同的图片，在渲染时出现了无dected文件夹的问题吗，这或许是在出现问题时被112行的“
        Recover.recover(Pictures_folder, parameter, 
                         parameter_json, yolov5_Path, system_name)”代码所恢复了初试，将json配置文件和dected文件夹重置了，你可以尝试删除此代码，或许可以解决问题或者获得更多错误详情

**Comment by PackageInstaller** [comment]
> > 重装了一下，还是 `以讲错误追加到 Imagelabels-err.txt` 这个提示，但是这个提示中以讲两个错别字只有在插件的recover.py中才有，去看了一下yolov5-master/runs这个文件夹，777权限不可能会创建文件夹失败，而且插件是能正常使用的，就很迷惑，究竟是哪里的问题？
> > ![image](https://user-images.githubusercontent.com/80018096/242828181-bd1e9c32-255c-441e-a397-64f8b203d9f6.png)
> 
> 你指的是发送两张相同的图片，在渲染时出现了无dected文件夹的问题吗，这或许是在出现问题时被112行的“ Recover.recover(Pictures_folder, parameter, parameter_json, yolov5_Path, system_name)”代码所恢复了初试，将json配置文件和dected文件夹重置了，你可以尝试删除此代码，或许可以解决问题或者获得更多错误详情

这里我是有两个问题的
1.插件加载时出现
```
可能由于没有权限所引发的异常，请尝试以管理员/root 身份运行bot,以讲错误追加到 Imagelabels-err.txt 
 错误代码：001 
 Possibly because of an exception thrown by not having permissions, try running bot as administrator/root to append the error to the Imagelabels-err.txt 
 Error code: 001
```
的提示，并且关掉机器人手动创建文件夹再启动后文件夹消失并且还是弹出这个错误

2.处理完毕后发出两张相同的图片

已删除112行代码，加载插件提示依旧在，并且还是两张同样的一起出来

**Comment by Heartestrella** [comment]
> > > 重装了一下，还是 `以讲错误追加到 Imagelabels-err.txt` 这个提示，但是这个提示中以讲两个错别字只有在插件的recover.py中才有，去看了一下yolov5-master/runs这个文件夹，777权限不可能会创建文件夹失败，而且插件是能正常使用的，就很迷惑，究竟是哪里的问题？
> > > ![image](https://user-images.githubusercontent.com/80018096/242828181-bd1e9c32-255c-441e-a397-64f8b203d9f6.png)
> > 
> > 你指的是发送两张相同的图片，在渲染时出现了无dected文件夹的问题吗，这或许是在出现问题时被112行的“ Recover.recover(Pictures_folder, parameter, parameter_json, yolov5_Path, system_name)”代码所恢复了初试，将json配置文件和dected文件夹重置了，你可以尝试删除此代码，或许可以解决问题或者获得更多错误详情
> 
> 这里我是有两个问题的
> 1.插件加载时出现
> ```
> 可能由于没有权限所引发的异常，请尝试以管理员/root 身份运行bot,以讲错误追加到 Imagelabels-err.txt 
>  错误代码：001 
>  Possibly because of an exception thrown by not having permissions, try running bot as administrator/root to append the error to the Imagelabels-err.txt 
>  Error code: 001
> ```
> 的提示，并且关掉机器人手动创建文件夹再启动后文件夹消失并且还是弹出这个错误
> 
> 2.处理完毕后发出两张相同的图片
> 
> 已删除112行代码，加载插件提示依旧在，并且还是两张同样的一起出来

依我的理解，我认为还是问题出现在了读写上，你是将整个bot文件夹设置了777权限吗？上次出现的问题是找不到dected文件夹，这次的问题依旧是找不到dected文件夹吗？

**Comment by PackageInstaller** [comment]
我是将bot目录底下所有子目录以及文件都设置了777权限

与其说找不到那个文件夹，不如说是在执行恢复的时候连同那个文件夹一起删除了？因为正常执行标注命令的时候又会自己创建好
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/e3a252b6-b41d-4fdb-b37d-bd1896ae5a76)

**Comment by PackageInstaller** [comment]
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/80c6a5da-9b3b-48be-95c9-cbaab348c386)

**Comment by Heartestrella** [comment]
> ![image](https://user-images.githubusercontent.com/80018096/243036760-80c6a5da-9b3b-48be-95c9-cbaab348c386.png)

那你可以直接尝试将init.py中的from nonebot_plugin_Imagelabels.recover import Recover 恢复命令直接删除，并将表用此库的代码全部注释了，那或许可以解决问题，我当初使用linux测试时并没有遇到此类问题，当为了防止出现意外，我设置了报错恢复初始的功能

**Comment by PackageInstaller** [comment]
我已将所有带有recover的都注释掉了，但是还是会自己自己删掉detect文件夹，并且在插件加载时报错（只是这次的报错只有一行）

**Comment by Heartestrella** [comment]
> 我已将所有带有recover的都注释掉了，但是还是会自己自己删掉detect文件夹，并且在插件加载时报错（只是这次的报错只有一行）

具体是什么，因为001错误出现在recover.py里，所以出现了具体的报错
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/110215026/77b96a88-17ad-44f7-914d-be6a956bbe1d)

**Comment by PackageInstaller** [comment]
> > 我已将所有带有recover的都注释掉了，但是还是会自己自己删掉detect文件夹，并且在插件加载时报错（只是这次的报错只有一行）
> 
> 具体是什么，因为001错误出现在recover.py里，所以出现了具体的报错 ![image](https://user-images.githubusercontent.com/110215026/243044026-77b96a88-17ad-44f7-914d-be6a956bbe1d.png)

001报错
Sat Jun  3 10:55:00 2023:[Errno 17] File exists: 'detect'

提前创建好的文件夹会在启动的时候删掉，报 File exists: 'detect'的错误

**Comment by Heartestrella** [comment]
> > > 我已将所有带有recover的都注释掉了，但是还是会自己自己删掉detect文件夹，并且在插件加载时报错（只是这次的报错只有一行）
> > 
> > 
> > 具体是什么，因为001错误出现在recover.py里，所以出现了具体的报错 ![image](https://user-images.githubusercontent.com/110215026/243044026-77b96a88-17ad-44f7-914d-be6a956bbe1d.png)
> 
> 001报错 Sat Jun 3 10:55:00 2023:[Errno 17] File exists: 'detect' 马萨卡，自己提前创建好也不行吗

不不不，这理论上没有问题，但是我认为这很奇怪，在recover.py中就算出现了错误恢复了默认，他有一行os.mkdir('detect')重新用于创建detect文件夹，不会出现消失的情况，我建议你使用pip uninstall  nonebot_plugin_Imagelabels 然后在bot目录下使用nb plugin install nonebot-plugin-Imagelabels 重新下载一遍，并将bot目录下的yolov5-master 和 Target_picture文件夹删除 再试试

**Comment by PackageInstaller** [comment]
> > > > 我已将所有带有recover的都注释掉了，但是还是会自己自己删掉detect文件夹，并且在插件加载时报错（只是这次的报错只有一行）
> > > 
> > > 
> > > 具体是什么，因为001错误出现在recover.py里，所以出现了具体的报错 ![image](https://user-images.githubusercontent.com/110215026/243044026-77b96a88-17ad-44f7-914d-be6a956bbe1d.png)
> > 
> > 
> > 001报错 Sat Jun 3 10:55:00 2023:[Errno 17] File exists: 'detect' 马萨卡，自己提前创建好也不行吗
> 
> 不不不，这理论上没有问题，但是我认为这很奇怪，在recover.py中就算出现了错误恢复了默认，他有一行os.mkdir('detect')重新用于创建detect文件夹，不会出现消失的情况，我建议你使用pip uninstall nonebot_plugin_Imagelabels 然后在bot目录下使用nb plugin install nonebot-plugin-Imagelabels 重新下载一遍，并将bot目录下的yolov5-master 和 Target_picture文件夹删除 再试试

我使用的是基于nonebot的zhenxun_bot,所以`nb plugin install nonebot-plugin-Imagelabels ` 指令我这边是没用的，安装插件都是git插件到插件目录来加载，以下是我的操作及响应

1.pip uninstall nonebot_plugin_Imagelabels

2.pip install nonebot_plugin_Imagelabels -U（不提前安装这个的话插件就会无法加载）
Successfully installed nonebot-plugin-imagelabels-1.0.0
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/7fae2e82-c67d-44aa-9ad3-9b3f11e5a217)


3.git clone https://github.com/istrashguy/nonebot_plugin_Imagelabels.git 到插件目录

4.启动bot

![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/f6b8a2b2-3154-4d9c-9df6-bf0b920bba79)
中间省略一大堆过程
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/007d5c43-f121-4aa0-a79b-69ecba9751a6)

5.执行图片标注指令，无响应

**Comment by PackageInstaller** [comment]
补充，下载的yolov5-master文件夹只有1.7m大小，这与我直接git的yolov5原项目的17m大小差太多了

**Comment by Heartestrella** [comment]
> 补充，下载的yolov5-master文件夹只有1.7m大小，这与我直接git的yolov5原项目的17m大小差太多了

1.大小问题，你可以参数自己git到目录下，我想应该是因为里面有个yolov5s.pt模型导致的差距
2.你没有删除bot目录下parameter.json导致了你上面的问题

**Comment by PackageInstaller** [comment]
> > 补充，下载的yolov5-master文件夹只有1.7m大小，这与我直接git的yolov5原项目的17m大小差太多了
> 
> 1.大小问题，你可以参数自己git到目录下，我想应该是因为里面有个yolov5s.pt模型导致的差距 2.你没有删除bot目录下parameter.json导致了你上面的问题

都删除了重来后
![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/0b906c7a-29e6-43b0-aaae-611949816efb)

新生成的parameter.json中内容是
{"sumber": 1, "Save_as": "Detect_targets", "yolov5_Path": "/home/Neko/Bot/zhenxun_bot/yolov5-master", "file_past": []}

**Comment by Heartestrella** [comment]
> > > 补充，下载的yolov5-master文件夹只有1.7m大小，这与我直接git的yolov5原项目的17m大小差太多了
> > 
> > 1.大小问题，你可以参数自己git到目录下，我想应该是因为里面有个yolov5s.pt模型导致的差距 2.你没有删除bot目录下parameter.json导致了你上面的问题
> 
> 都删除了重来后
> ![image](https://github.com/istrashguy/nonebot_plugin_Imagelabels/assets/80018096/0b906c7a-29e6-43b0-aaae-611949816efb)
> 
> 新生成的parameter.json中内容是
> {"sumber": 1, "Save_as": "Detect_targets", "yolov5_Path": "/home/Neko/Bot/zhenxun_bot/yolov5-master", "file_past": []}
> 

如果你自己下载了yolov5放在bot目录，则无法自动获取到路径，这时候你自己配置一下json里的yolov5_path对应的路径就行，然后重启bot问题应该就不存在了
主要是我没用过真寻，不了解与nonebot有什么差别，所以解决起来比较麻烦

**Comment by PackageInstaller** [comment]
> > > > 补充，下载的yolov5-master文件夹只有1.7m大小，这与我直接git的yolov5原项目的17m大小差太多了
> > > 
> > > 
> > > 1.大小问题，你可以参数自己git到目录下，我想应该是因为里面有个yolov5s.pt模型导致的差距 2.你没有删除bot目录下parameter.json导致了你上面的问题
> > 
> > 
> > 都删除了重来后
> > ![image](https://user-images.githubusercontent.com/80018096/243047618-0b906c7a-29e6-43b0-aaae-611949816efb.png)
> > 新生成的parameter.json中内容是
> > {"sumber": 1, "Save_as": "Detect_targets", "yolov5_Path": "/home/Neko/Bot/zhenxun_bot/yolov5-master", "file_past": []}
> 
> 如果你自己下载了yolov5放在bot目录，则无法自动获取到路径，这时候你自己配置一下json里的yolov5_path对应的路径就行，然后重启bot问题应该就不存在了 主要是我没用过真寻，不了解与nonebot有什么差别，所以解决起来比较麻烦

这个是他自己默认下载的，我什么都没做

**Comment by PackageInstaller** [comment]
重启bot后报错消失，也能用了，但是还是两张图，累了，能跑就行

**Comment by Heartestrella** [comment]
> 重启bot后报错消失，也能用了，但是还是两张图，累了，能跑就行

可能是因为你用的是真寻，在我之前测试时并没有遇到过这些问题，不过解决了问题就算是好的了，抱歉给你带来了困扰
